// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO conversation_participants (
    conversation_id,
    user_id,
    role
) VALUES (
    $1, $2, $3
) RETURNING conversation_id, user_id, joined_at, role
`

type AddParticipantParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	UserID         uuid.UUID `json:"userId"`
	Role           string    `json:"role"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (ConversationParticipant, error) {
	row := q.db.QueryRow(ctx, addParticipant, arg.ConversationID, arg.UserID, arg.Role)
	var i ConversationParticipant
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.JoinedAt,
		&i.Role,
	)
	return i, err
}

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO message_attachments (
    message_id,
    file_url,
    file_type,
    file_name
) VALUES (
    $1, $2, $3, $4
)
`

type CreateAttachmentParams struct {
	MessageID uuid.UUID `json:"messageId"`
	FileUrl   string    `json:"fileUrl"`
	FileType  string    `json:"fileType"`
	FileName  string    `json:"fileName"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.Exec(ctx, createAttachment,
		arg.MessageID,
		arg.FileUrl,
		arg.FileType,
		arg.FileName,
	)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
    name,
    type
) VALUES (
    $1, $2
) RETURNING id, name, type, created_at, last_message_at
`

type CreateConversationParams struct {
	Name pgtype.Text `json:"name"`
	Type string      `json:"type"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Name, arg.Type)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    conversation_id,
    sender_id,
    content
) VALUES (
    $1, $2, $3
) RETURNING id, conversation_id, sender_id, content, created_at, updated_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	SenderID       uuid.UUID `json:"senderId"`
	Content        string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findExistingPrivateChat = `-- name: FindExistingPrivateChat :one
SELECT c.id
FROM conversations c
JOIN conversation_participants cp1 ON c.id = cp1.conversation_id
JOIN conversation_participants cp2 ON c.id = cp2.conversation_id
WHERE c.type = 'private'
    AND cp1.user_id = $1
    AND cp2.user_id = $2
LIMIT 1
`

type FindExistingPrivateChatParams struct {
	UserID   uuid.UUID `json:"userId"`
	UserID_2 uuid.UUID `json:"userId2"`
}

func (q *Queries) FindExistingPrivateChat(ctx context.Context, arg FindExistingPrivateChatParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findExistingPrivateChat, arg.UserID, arg.UserID_2)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, name, type, created_at, last_message_at FROM conversations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT
    m.id,
    m.conversation_id,
    m.sender_id,
    m.content,
    m.created_at,
    m.updated_at,
    COALESCE(
        json_agg(
        json_build_object(
            'id', ma.id,
            'url', ma.file_url,
            'type', ma.file_type,
            'name', ma.file_name
        )
    ) FILTER (WHERE ma.id IS NOT NULL),
        '[]'
    )::jsonb AS attachments
FROM messages m
LEFT JOIN message_attachments ma ON m.id = ma.message_id
WHERE m.conversation_id = $1
GROUP BY m.id, m.created_at
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type GetConversationMessagesParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

type GetConversationMessagesRow struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversationId"`
	SenderID       uuid.UUID          `json:"senderId"`
	Content        string             `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	Attachments    []byte             `json:"attachments"`
}

// GetConversationMessages Loads messages for a specific chat with pagination support
func (q *Queries) GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]GetConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, getConversationMessages, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMessagesRow
	for rows.Next() {
		var i GetConversationMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Attachments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipant = `-- name: GetParticipant :one
SELECT conversation_id, user_id, joined_at, role FROM conversation_participants
WHERE conversation_id = $1 AND user_id = $2
LIMIT 1
`

type GetParticipantParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	UserID         uuid.UUID `json:"userId"`
}

func (q *Queries) GetParticipant(ctx context.Context, arg GetParticipantParams) (ConversationParticipant, error) {
	row := q.db.QueryRow(ctx, getParticipant, arg.ConversationID, arg.UserID)
	var i ConversationParticipant
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.JoinedAt,
		&i.Role,
	)
	return i, err
}

const getUserConversations = `-- name: GetUserConversations :many
SELECT
    c.id,
    c.name,
    c.type,
    c.created_at,
    c.last_message_at,
    cp.role,
    cp.joined_at
FROM conversations c
JOIN conversation_participants cp ON c.id = cp.conversation_id
WHERE cp.user_id = $1
ORDER BY c.last_message_at DESC
`

type GetUserConversationsRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Type          string             `json:"type"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	LastMessageAt pgtype.Timestamptz `json:"lastMessageAt"`
	Role          string             `json:"role"`
	JoinedAt      pgtype.Timestamptz `json:"joinedAt"`
}

// GetUserConversations lists all the conversations a user is part of
func (q *Queries) GetUserConversations(ctx context.Context, userID uuid.UUID) ([]GetUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, getUserConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserConversationsRow
	for rows.Next() {
		var i GetUserConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.LastMessageAt,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationLastMessageAt = `-- name: UpdateConversationLastMessageAt :exec
UPDATE conversations
SET last_message_at = $2
WHERE id = $1
`

type UpdateConversationLastMessageAtParams struct {
	ID            uuid.UUID          `json:"id"`
	LastMessageAt pgtype.Timestamptz `json:"lastMessageAt"`
}

func (q *Queries) UpdateConversationLastMessageAt(ctx context.Context, arg UpdateConversationLastMessageAtParams) error {
	_, err := q.db.Exec(ctx, updateConversationLastMessageAt, arg.ID, arg.LastMessageAt)
	return err
}
