// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO conversation_participants (
    conversation_id,
    user_id,
    role
) VALUES (
    $1, $2, $3
) RETURNING conversation_id, user_id, joined_at, role, last_read_at
`

type AddParticipantParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	UserID         uuid.UUID `json:"userId"`
	Role           string    `json:"role"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (ConversationParticipant, error) {
	row := q.db.QueryRow(ctx, addParticipant, arg.ConversationID, arg.UserID, arg.Role)
	var i ConversationParticipant
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.JoinedAt,
		&i.Role,
		&i.LastReadAt,
	)
	return i, err
}

const countRemainingAdmins = `-- name: CountRemainingAdmins :one
SELECT COUNT(*) FROM conversation_participants
WHERE conversation_id = $1
  AND role IN ('admin', 'creator')
  AND user_id != $2
`

type CountRemainingAdminsParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	UserID         uuid.UUID `json:"userId"`
}

func (q *Queries) CountRemainingAdmins(ctx context.Context, arg CountRemainingAdminsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRemainingAdmins, arg.ConversationID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO message_attachments (
    message_id,
    file_url,
    file_type,
    file_name
) VALUES (
    $1, $2, $3, $4
)
`

type CreateAttachmentParams struct {
	MessageID uuid.UUID `json:"messageId"`
	FileUrl   string    `json:"fileUrl"`
	FileType  string    `json:"fileType"`
	FileName  string    `json:"fileName"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.Exec(ctx, createAttachment,
		arg.MessageID,
		arg.FileUrl,
		arg.FileType,
		arg.FileName,
	)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
    name,
    type,
    avatar_url
) VALUES (
    $1, $2, $3
) RETURNING id, name, type, avatar_url, created_at, last_message_at
`

type CreateConversationParams struct {
	Name      pgtype.Text `json:"name"`
	Type      string      `json:"type"`
	AvatarUrl string      `json:"avatarUrl"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Name, arg.Type, arg.AvatarUrl)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    conversation_id,
    sender_id,
    content
) VALUES (
    $1, $2, $3
) RETURNING id, conversation_id, sender_id, content, created_at, updated_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	SenderID       uuid.UUID `json:"senderId"`
	Content        string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const findExistingPrivateChat = `-- name: FindExistingPrivateChat :one
SELECT c.id
FROM conversations c
JOIN conversation_participants cp1 ON c.id = cp1.conversation_id
JOIN conversation_participants cp2 ON c.id = cp2.conversation_id
WHERE c.type = 'private'
    AND cp1.user_id = $1
    AND cp2.user_id = $2
LIMIT 1
`

type FindExistingPrivateChatParams struct {
	UserID   uuid.UUID `json:"userId"`
	UserID_2 uuid.UUID `json:"userId2"`
}

func (q *Queries) FindExistingPrivateChat(ctx context.Context, arg FindExistingPrivateChatParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findExistingPrivateChat, arg.UserID, arg.UserID_2)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAdminParticipants = `-- name: GetAdminParticipants :many
SELECT user_id FROM conversation_participants
WHERE conversation_id = $1 AND role IN ('admin', 'creator')
`

func (q *Queries) GetAdminParticipants(ctx context.Context, conversationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAdminParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversation = `-- name: GetConversation :one
SELECT id, name, type, avatar_url, created_at, last_message_at FROM conversations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT
    m.id,
    m.conversation_id,
    m.sender_id,
    m.content,
    m.created_at,
    m.updated_at,
    u.username AS sender_username,
    u.first_name AS sender_first_name,
    u.last_name AS sender_last_name,
    u.avatar_url AS sender_avatar_url,
    COALESCE(
        json_agg(
        json_build_object(
            'id', ma.id,
            'url', ma.file_url,
            'type', ma.file_type,
            'name', ma.file_name
        )
    ) FILTER (WHERE ma.id IS NOT NULL),
        '[]'
    )::jsonb AS attachments
FROM messages m
JOIN users u ON m.sender_id = u.id
LEFT JOIN message_attachments ma ON m.id = ma.message_id
WHERE m.conversation_id = $1
GROUP BY
    m.id,
    m.created_at,
    u.username,
    u.first_name,
    u.last_name,
    u.avatar_url
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type GetConversationMessagesParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

type GetConversationMessagesRow struct {
	ID              uuid.UUID          `json:"id"`
	ConversationID  uuid.UUID          `json:"conversationId"`
	SenderID        uuid.UUID          `json:"senderId"`
	Content         string             `json:"content"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	SenderUsername  string             `json:"senderUsername"`
	SenderFirstName string             `json:"senderFirstName"`
	SenderLastName  string             `json:"senderLastName"`
	SenderAvatarUrl pgtype.Text        `json:"senderAvatarUrl"`
	Attachments     []byte             `json:"attachments"`
}

// GetConversationMessages Loads messages for a specific chat with pagination support
func (q *Queries) GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]GetConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, getConversationMessages, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMessagesRow
	for rows.Next() {
		var i GetConversationMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SenderUsername,
			&i.SenderFirstName,
			&i.SenderLastName,
			&i.SenderAvatarUrl,
			&i.Attachments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationParticipants = `-- name: GetConversationParticipants :many
SELECT user_id FROM conversation_participants
WHERE conversation_id = $1
`

func (q *Queries) GetConversationParticipants(ctx context.Context, conversationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getConversationParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationParticipantsDetailed = `-- name: GetConversationParticipantsDetailed :many
SELECT
    u.id,
    u.username,
    u.first_name,
    u.last_name,
    u.avatar_url,
    cp.role,
    cp.joined_at
FROM conversation_participants cp
JOIN users u ON cp.user_id = u.id
WHERE cp.conversation_id = $1
ORDER BY
    -- This clever trick sorts 'creator' and 'admin' at the top of the list!
    CASE cp.role
        WHEN 'creator' THEN 1
        WHEN 'admin' THEN 2
        ELSE 3
    END,
    cp.joined_at
`

type GetConversationParticipantsDetailedRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	FirstName string             `json:"firstName"`
	LastName  string             `json:"lastName"`
	AvatarUrl pgtype.Text        `json:"avatarUrl"`
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joinedAt"`
}

// GetConversationParticipantsDetailed fetches full user profiles and roles for a chat
func (q *Queries) GetConversationParticipantsDetailed(ctx context.Context, conversationID uuid.UUID) ([]GetConversationParticipantsDetailedRow, error) {
	rows, err := q.db.Query(ctx, getConversationParticipantsDetailed, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationParticipantsDetailedRow
	for rows.Next() {
		var i GetConversationParticipantsDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, sender_id, content, created_at, updated_at FROM messages
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOldestRemainingParticipant = `-- name: GetOldestRemainingParticipant :one
SELECT user_id FROM conversation_participants
WHERE conversation_id = $1 AND user_id != $2
ORDER BY joined_at
LIMIT 1
`

type GetOldestRemainingParticipantParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	UserID         uuid.UUID `json:"userId"`
}

func (q *Queries) GetOldestRemainingParticipant(ctx context.Context, arg GetOldestRemainingParticipantParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOldestRemainingParticipant, arg.ConversationID, arg.UserID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT conversation_id, user_id, joined_at, role, last_read_at FROM conversation_participants
WHERE conversation_id = $1 AND user_id = $2
LIMIT 1
`

type GetParticipantParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	UserID         uuid.UUID `json:"userId"`
}

func (q *Queries) GetParticipant(ctx context.Context, arg GetParticipantParams) (ConversationParticipant, error) {
	row := q.db.QueryRow(ctx, getParticipant, arg.ConversationID, arg.UserID)
	var i ConversationParticipant
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.JoinedAt,
		&i.Role,
		&i.LastReadAt,
	)
	return i, err
}

const getParticipantRole = `-- name: GetParticipantRole :one
SELECT role FROM conversation_participants
WHERE conversation_id = $1 AND user_id = $2
`

type GetParticipantRoleParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	UserID         uuid.UUID `json:"userId"`
}

func (q *Queries) GetParticipantRole(ctx context.Context, arg GetParticipantRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getParticipantRole, arg.ConversationID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUserConversations = `-- name: GetUserConversations :many
SELECT
    c.id,
    c.name,
    c.type,
    c.created_at,
    c.last_message_at,
    cp.role,
    cp.joined_at,
    (SELECT content FROM messages m WHERE m.conversation_id = c.id ORDER BY m.created_at DESC LIMIT 1) AS last_message,
    -- Fetch the "Other User" info (Nullable, only for private chats)
    u.username AS other_username,
    u.first_name AS other_first_name,
    u.last_name AS other_last_name,
    u.bio AS other_bio,
    u.avatar_url AS other_avatar_url
FROM conversations c
JOIN conversation_participants cp ON c.id = cp.conversation_id
LEFT JOIN conversation_participants cp2
    ON c.id = cp2.conversation_id
    AND cp2.user_id != $1
    AND c.type = 'private'
LEFT JOIN users u ON cp2.user_id = u.id
WHERE cp.user_id = $1
ORDER BY c.last_message_at DESC
`

type GetUserConversationsRow struct {
	ID             uuid.UUID          `json:"id"`
	Name           pgtype.Text        `json:"name"`
	Type           string             `json:"type"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	LastMessageAt  pgtype.Timestamptz `json:"lastMessageAt"`
	Role           string             `json:"role"`
	JoinedAt       pgtype.Timestamptz `json:"joinedAt"`
	LastMessage    string             `json:"lastMessage"`
	OtherUsername  pgtype.Text        `json:"otherUsername"`
	OtherFirstName pgtype.Text        `json:"otherFirstName"`
	OtherLastName  pgtype.Text        `json:"otherLastName"`
	OtherBio       pgtype.Text        `json:"otherBio"`
	OtherAvatarUrl pgtype.Text        `json:"otherAvatarUrl"`
}

// GetUserConversations lists all the conversations a user is part of
// Logic: If type is 'private', find the participant who is NOT me ($1)
func (q *Queries) GetUserConversations(ctx context.Context, userID uuid.UUID) ([]GetUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, getUserConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserConversationsRow
	for rows.Next() {
		var i GetUserConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.LastMessageAt,
			&i.Role,
			&i.JoinedAt,
			&i.LastMessage,
			&i.OtherUsername,
			&i.OtherFirstName,
			&i.OtherLastName,
			&i.OtherBio,
			&i.OtherAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalSearch = `-- name: GlobalSearch :many
SELECT
    id,
    'user'::varchar AS result_type,
    username,
    first_name,
    last_name,
    avatar_url,
    username AS search_name -- Used just for sorting
FROM users
WHERE username ILIKE '%' || $3::text || '%'
   OR first_name ILIKE '%' || $3::text || '%'
   OR last_name ILIKE '%' || $3::text || '%'

UNION ALL

SELECT
    id,
    'channel'::varchar AS result_type,
    ''::varchar AS username,
    ''::varchar AS first_name,
    ''::varchar AS last_name,
    ''::varchar AS avatar_url,
    name AS search_name
FROM conversations
WHERE type = 'channel'
  AND name ILIKE '%' || $3::text || '%'

ORDER BY result_type, search_name
LIMIT $1 OFFSET $2
`

type GlobalSearchParams struct {
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
	SearchQuery string `json:"searchQuery"`
}

type GlobalSearchRow struct {
	ID         uuid.UUID   `json:"id"`
	ResultType string      `json:"resultType"`
	Username   string      `json:"username"`
	FirstName  string      `json:"firstName"`
	LastName   string      `json:"lastName"`
	AvatarUrl  pgtype.Text `json:"avatarUrl"`
	SearchName string      `json:"searchName"`
}

func (q *Queries) GlobalSearch(ctx context.Context, arg GlobalSearchParams) ([]GlobalSearchRow, error) {
	rows, err := q.db.Query(ctx, globalSearch, arg.Limit, arg.Offset, arg.SearchQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalSearchRow
	for rows.Next() {
		var i GlobalSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.ResultType,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.SearchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipants = `-- name: ListParticipants :many
SELECT
    u.username,
    u.avatar_url,
    cp.user_id,
    cp.role,
    cp.joined_at
FROM conversation_participants cp
JOIN users u ON cp.user_id = u.id
WHERE cp.conversation_id = $1
ORDER BY cp.role, u.username
`

type ListParticipantsRow struct {
	Username  string             `json:"username"`
	AvatarUrl pgtype.Text        `json:"avatarUrl"`
	UserID    uuid.UUID          `json:"userId"`
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joinedAt"`
}

func (q *Queries) ListParticipants(ctx context.Context, conversationID uuid.UUID) ([]ListParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantsRow
	for rows.Next() {
		var i ListParticipantsRow
		if err := rows.Scan(
			&i.Username,
			&i.AvatarUrl,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeParticipant = `-- name: RemoveParticipant :exec
DELETE FROM conversation_participants
WHERE conversation_id = $1 AND user_id = $2
`

type RemoveParticipantParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	UserID         uuid.UUID `json:"userId"`
}

func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error {
	_, err := q.db.Exec(ctx, removeParticipant, arg.ConversationID, arg.UserID)
	return err
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations
SET name = $2
WHERE id = $1
RETURNING id, name, type, avatar_url, created_at, last_message_at
`

type UpdateConversationParams struct {
	ID   uuid.UUID   `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversation, arg.ID, arg.Name)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const updateConversationLastMessageAt = `-- name: UpdateConversationLastMessageAt :exec
UPDATE conversations
SET last_message_at = $2
WHERE id = $1
`

type UpdateConversationLastMessageAtParams struct {
	ID            uuid.UUID          `json:"id"`
	LastMessageAt pgtype.Timestamptz `json:"lastMessageAt"`
}

func (q *Queries) UpdateConversationLastMessageAt(ctx context.Context, arg UpdateConversationLastMessageAtParams) error {
	_, err := q.db.Exec(ctx, updateConversationLastMessageAt, arg.ID, arg.LastMessageAt)
	return err
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
SET content = $2, updated_at = now()
WHERE id = $1
RETURNING id, conversation_id, sender_id, content, created_at, updated_at
`

type UpdateMessageParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParticipantLastRead = `-- name: UpdateParticipantLastRead :exec
UPDATE conversation_participants
SET last_read_at = now()
WHERE conversation_id = $1 AND user_id = $2
`

type UpdateParticipantLastReadParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	UserID         uuid.UUID `json:"userId"`
}

func (q *Queries) UpdateParticipantLastRead(ctx context.Context, arg UpdateParticipantLastReadParams) error {
	_, err := q.db.Exec(ctx, updateParticipantLastRead, arg.ConversationID, arg.UserID)
	return err
}

const updateParticipantRole = `-- name: UpdateParticipantRole :exec
UPDATE conversation_participants
SET role = $3
WHERE conversation_id = $1 AND user_id = $2
`

type UpdateParticipantRoleParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	UserID         uuid.UUID `json:"userId"`
	Role           string    `json:"role"`
}

func (q *Queries) UpdateParticipantRole(ctx context.Context, arg UpdateParticipantRoleParams) error {
	_, err := q.db.Exec(ctx, updateParticipantRole, arg.ConversationID, arg.UserID, arg.Role)
	return err
}
