// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeConversationInvite = `-- name: ConsumeConversationInvite :one
UPDATE conversation_invites
SET uses_count = uses_count + 1
WHERE token = $1 AND uses_count < max_uses AND expires_at > NOW()
RETURNING token, conversation_id, created_by, max_uses, uses_count, expires_at, created_at
`

func (q *Queries) ConsumeConversationInvite(ctx context.Context, token string) (ConversationInvite, error) {
	row := q.db.QueryRow(ctx, consumeConversationInvite, token)
	var i ConversationInvite
	err := row.Scan(
		&i.Token,
		&i.ConversationID,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createConversationInvite = `-- name: CreateConversationInvite :one
INSERT INTO conversation_invites (
    token,
    conversation_id,
    created_by,
    max_uses,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING token, conversation_id, created_by, max_uses, uses_count, expires_at, created_at
`

type CreateConversationInviteParams struct {
	Token          string             `json:"token"`
	ConversationID uuid.UUID          `json:"conversationId"`
	CreatedBy      uuid.UUID          `json:"createdBy"`
	MaxUses        int32              `json:"maxUses"`
	ExpiresAt      pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) CreateConversationInvite(ctx context.Context, arg CreateConversationInviteParams) (ConversationInvite, error) {
	row := q.db.QueryRow(ctx, createConversationInvite,
		arg.Token,
		arg.ConversationID,
		arg.CreatedBy,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i ConversationInvite
	err := row.Scan(
		&i.Token,
		&i.ConversationID,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConversationInvite = `-- name: DeleteConversationInvite :exec
DELETE FROM conversation_invites
WHERE token = $1
`

func (q *Queries) DeleteConversationInvite(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteConversationInvite, token)
	return err
}

const getConversationInvite = `-- name: GetConversationInvite :one
SELECT token, conversation_id, created_by, max_uses, uses_count, expires_at, created_at FROM conversation_invites
WHERE token = $1 LIMIT 1
`

func (q *Queries) GetConversationInvite(ctx context.Context, token string) (ConversationInvite, error) {
	row := q.db.QueryRow(ctx, getConversationInvite, token)
	var i ConversationInvite
	err := row.Scan(
		&i.Token,
		&i.ConversationID,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveInvitesForConversation = `-- name: ListActiveInvitesForConversation :many
SELECT token, conversation_id, created_by, max_uses, uses_count, expires_at, created_at FROM conversation_invites
WHERE conversation_id = $1 AND uses_count < max_uses AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveInvitesForConversation(ctx context.Context, conversationID uuid.UUID) ([]ConversationInvite, error) {
	rows, err := q.db.Query(ctx, listActiveInvitesForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationInvite
	for rows.Next() {
		var i ConversationInvite
		if err := rows.Scan(
			&i.Token,
			&i.ConversationID,
			&i.CreatedBy,
			&i.MaxUses,
			&i.UsesCount,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
