// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID            uuid.UUID          `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Type          string             `json:"type"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	LastMessageAt pgtype.Timestamptz `json:"lastMessageAt"`
}

type ConversationParticipant struct {
	ConversationID uuid.UUID          `json:"conversationId"`
	UserID         uuid.UUID          `json:"userId"`
	JoinedAt       pgtype.Timestamptz `json:"joinedAt"`
	Role           string             `json:"role"`
}

type Message struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversationId"`
	SenderID       uuid.UUID          `json:"senderId"`
	Content        string             `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type Session struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"userId"`
	RefreshToken string             `json:"refreshToken"`
	UserAgent    string             `json:"userAgent"`
	ClientIp     string             `json:"clientIp"`
	IsBlocked    bool               `json:"isBlocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"passwordHash"`
	FirstName    string             `json:"firstName"`
	LastName     string             `json:"lastName"`
	Bio          pgtype.Text        `json:"bio"`
	Birthday     pgtype.Date        `json:"birthday"`
	AvatarUrl    pgtype.Text        `json:"avatarUrl"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}
